### ISSUE TITLE
HashMap in C#

### ISSUE THREAD

**Issue by ridz0326** [ridz0326/Hash-Map#11]
- Introduction to HashMap
- Complete explanation on HashMap
- Code for Insertion Operation in HashMap
- Explanation of Code Example

**Comment by ManasBhilare** [comment]
I would like to work on this issue.

**Comment by iaryangoyal** [comment]
I would like to work on this issue. @ridz0326

**Comment by viren76** [comment]
I would like to work on this issue. Please assign me
